### ISSUE TITLE
Item tracking causing problems in PSO BB

### ISSUE THREAD

**Issue by patapancakes** [fuzziqersoftware/newserv#32]
On a newserv instance I run there's a pretty bad problem with users being disconnected when using or picking up items, the cause of which being item tracking.

```
I 91611 2022-08-02 23:03:48 - [Commands] Received from C-57 (Luma) (version=BB command=0062 flag=00000000)
0000000000000000 | 14 00 62 00 00 00 00 00 5A 03 02 00 0A 00 81 00 |   b     Z
0000000000000010 | 01 00 00 00                                     |
W 91611 2022-08-02 23:03:48 - [Server] Error processing client command: item not present

I 91611 2022-08-02 23:07:43 - [Commands] Received from C-63 (Luma) (version=BB command=0062 flag=00000000)
0000000000000000 | 14 00 62 00 00 00 00 00 5A 03 02 00 12 00 81 00 |   b     Z
0000000000000010 | 01 00 00 00                                     |
W 91611 2022-08-02 23:07:43 - [Server] Error processing client command: item not present

I 91611 2022-08-03 00:12:04 - [Commands] Received from C-69 (Lead) (version=BB command=0062 flag=00000000)
0000000000000000 | 14 00 62 00 00 00 00 00 5A 03 01 00 9F 00 81 00 |   b     Z
0000000000000010 | 01 00 00 00                                     |
W 91611 2022-08-03 00:12:04 - [Server] Error processing client command: inventory is full

I 91611 2022-08-03 00:25:28 - [Commands] Received from C-CC (Lead) (version=BB command=0062 flag=00000001)
0000000000000000 | 14 00 62 00 01 00 00 00 5A 03 01 00 A0 00 81 00 |   b     Z
0000000000000010 | 03 00 00 00                                     |
W 91611 2022-08-03 00:25:28 - [Server] Error processing client command: inventory is full
```

Some examples of the errors above. I'm disabling item tracking for now to get past this.

**Comment by fuzziqersoftware** [comment]
I suspect things will break even worse with item tracking disabled, since on BB the server needs to know about a lot of things that it didn't need to do on older versions. Can you share a full log of the session in which this happened?

**Comment by Gamizard** [comment]
The log from that session would be too big to send so I got a player to try and recreate those problems. Not exactly the same errors as earlier but still crashes related to items.

[http://majestaria.fun/error.log](url)

**Comment by fuzziqersoftware** [comment]
This log shows a player attempting to use the tekker window. I've implemented the tekker window, so this should now work. I haven't implemented the shop windows properly yet though; the shops will probably contain weird-looking items and items can't be bought or sold.

**Comment by Gamizard** [comment]
If I start seeing the original error I mentioned again I'll post the log for it.

**Comment by Gamizard** [comment]
After further testing it seems like this is only happening if the player is in a part with other people, we can't get it to happen if they're playing solo.

**Comment by Gamizard** [comment]
```
I 99062 2022-08-04 01:55:46 - [Commands] Received from C-1A (Murasaki) (version=BB command=0062 flag=00000000)
0000000000000000 | 14 00 62 00 00 00 00 00 5A 03 00 00 A6 00 81 00 |   b     Z
0000000000000010 | 00 00 00 00                                     |
W 99062 2022-08-04 01:55:46 - [Server] Error processing client command: item not present
I 99062 2022-08-04 01:55:46 - [Server] Client disconnected: C-1A on fd 13
```

There was a dropped Scape Doll that crashed anyone that tried to pick it up. Weird stuff, server/client data mismatch?

**Comment by rumatsuki** [comment]
```
I 225992 2023-03-13 20:29:46 - [Commands] Received from C-4C (Nish      Eiki) (version=BB command=0060 flag=00000000)
0000 | 10 00 60 00 00 00 00 00 27 02 01 00 09 00 21 00 |   `     '     !
W 225992 2023-03-13 20:29:46 - [Server] Error processing client command: item not present
I 225992 2023-03-13 20:29:46 - [Server] Client disconnected: C-4C on fd 16
```
It seems this still happens even when the patch-bb folder has the client's data files in it. Is there anything I'm missing?

**Comment by rumatsuki** [comment]
Small update if it's of any help, it seems to primarily happen when two players try to pick up the same item quickly.

**Comment by fuzziqersoftware** [comment]
Can you provide a full log? It's hard to know what exactly is going wrong without seeing the game history from the beginning.

**Comment by fuzziqersoftware** [comment]
Several item-related bugs have been fixed in the past few weeks, and I expect BB games to be more stable now. Probably the issues you saw in this thread have been fixed along with the others, but please feel free to open a new ticket here if there are further problems.
