### ISSUE TITLE
Better support for PSO BB

### ISSUE THREAD

**Issue by patapancakes** [fuzziqersoftware/newserv#38]
Hello! This is less of a specific issue and more regarding general improvement of PSO BB support on newserv. I have a Tethealla-based client and community of around 10 players able to help playtest and report bugs. Is there a faster or more organized way to get these reports to you other than GitHub issues? I'd love to help out in any way I can as it seems no other modern server is close to having good support yet.

Thanks.

**Comment by fuzziqersoftware** [comment]
Probably GitHub issues are the best way; this is a personal project of mine and I can't consistently dedicate time to it. PRs are welcome as well as issues, but I doubt others have interest or time to improve newserv as well.

My impression is that the public version of Tethealla is the server of choice for private PSOBB communities, which is why I haven't spent much time on newserv's BB implementation. Are there specific needs / features that Tethealla doesn't fulfill?

**Comment by Gamizard** [comment]
(Strangely, my original reply disappeared.)

I see, I'll continue using issues then.

My problem with the Tethealla server is the overall lack of portability (compared to newserv) on top of it no longer being maintained (it also seems pretty messy after some looking). I personally really like how newserv is laid out, having multiple games and different servers running in a single process has made it incredibly easy to update and install as a service to run in the background.

**Comment by Gamizard** [comment]
Does newserv try to use the maps in the patch server folder if they exist? I just now went and symlinked the maps into the blueburst maps folder but it would be helpful if this could be done automatically.

**Comment by fuzziqersoftware** [comment]
It does use the files from the patch-bb directory (specifically, system/patch-bb/data/map_*.dat). If the map isn't found there, it then looks in data.gsl (which is what the client does as well). If the map isn't found in either of those places, it falls back to the files in system/blueburst.

I'm still working on the incorrect EXP values for various enemies. The way PSO assigns enemy IDs is unwieldy, and it's easy for a small mistake to affect every enemy in the game.

**Comment by Gamizard** [comment]
Alright, good to know then.

I'll be able to test the EXP fixes whenever they're ready.

**Comment by Gamizard** [comment]
Hmm, I'm not sure of any good places to ask this but do you (or anyone else) know where to find a clean copy of the game data for PSOBB? I'm only having luck finding versions modified by other private servers and nothing that seems to be intact.

**Comment by hegyak** [comment]
> Hmm, I'm not sure of any good places to ask this but do you (or anyone else) know where to find a clean copy of the game data for PSOBB? I'm only having luck finding versions modified by other private servers and nothing that seems to be intact.

Hello.  I think this may be what you are looking for.
https://archive.org/details/psobb

It's only the Japanese Version.  I don't know where a Clean PSO:BB English ISO can be found.  Maby, by comparing the Clean Japanese version to the Private Server English version, you can find the change(s) that were done to make the game work on Private servers.

Just trying to help, how I can.

**Comment by ShiftaDeband** [comment]
> My impression is that the public version of Tethealla is the server of choice for private PSOBB communities, which is why I haven't spent much time on newserv's BB implementation. Are there specific needs / features that Tethealla doesn't fulfill?

Just my +1 here - there aren't many options that support Blue Burst out there aside from Tethealla, and that doesn't have other platform compatibility that this server does. I believe Sylverant has some code for it, but I don't think it will ever be fully implemented. This is also the only server that I can get to work with a 'clean' 1.24.3 US Blue Burst installation.

I hope that as time goes on, this could be the 'swiss-army knife' of PSO servers for a lot of reasons. It's great for testing, very helpful for historical documentation, and just in general a very well done (and well documented) project.

**Comment by fuzziqersoftware** [comment]
I can't promise I'll have time to spend on BB in the near future - getting BB to work properly is a much more involved subproject than most other parts of newserv have been. I've fixed almost all EXP mismatches in Episode 1 (only Dark Falz's EXP is incorrect), but a lot of work remains - most notably, common item drops aren't at all like they should be, and shops don't work. It's nice to know that others care about this functionality; I've added a list of tasks to get BB to a playable state in the readme, and will work on them as time allows.

**Comment by Sazonde99** [comment]
> 

From what I've been told, the JP version of Blue Burst is preferred for private servers as it received some items and quests that US never got. It's unfortunate that no one has uploaded clean end of service files though. I have no idea if there were any additional patches post-launch since it's been too long.

On a different note, newserv Blue Burst interests me as well. There are some issues that are still unresolved on Tethealla that I'll try to confirm on newserv before reporting. As the others have mentioned, newserv is still maintained and I love that it's all-encompassing like an entire PSO ecosystem. Definitely appreciate the work done here.

**Comment by PalasX** [comment]
Just off the top of my head, i believe the public release of Tethealla has issues with:
Accessing bank in game after selling items in shop causes desync and game drop. caused by server/client mismatch of meseta amount, caused by incorrect calculation of sale price of items.
Shops are not generated per rules based on player levels, they are pre-recorded shops from original PSOBB servers that are then "played back" to the client.
Challenge modes are not implemented.
Trade window is not implemented.
Server and MySQL/MariaDB disconnect after about a week online. Seems to be a known issue, required cron job to restart server every week.

There is a fork that compiles on linux, to which ive contributed a couple fixes and some QoL chat commands:
https://gitlab.com/theodis3/tethealla
It still needs all the support-files form the Windows version, and a lot of the text files must be manually converted from CR/LF to just LF (dos2unix).

The public release of Tethealla DOES support the JP-only items when using a properly patched client. I have a copy of the patcher and a pre-modded client psobb.exe if you need it for anything.

**Comment by Sazonde99** [comment]
Commander Blade is still not fixed even on live Ephinea. Supposed to grant +20 ATA to your teammates when wielded by a Team Master. Also the lack of units with suffixes (--, -, +, ++). I assume the open fork probably doesn't have Coren?

**Comment by fuzziqersoftware** [comment]
Since the time this issue was opened, newserv's PSOBB support has improved quite a bit:
* Battle and Challenge modes are implemented
* Trade window is implemented
* All one-off quest subcommands are implemented (though many are not well-tested; there could still be bugs here)
* Teams and team rewards are implemented
* Quest progression is implemented
* Enemy loading now appears to be fully correct; haven't seen any mismatches in EXP or item drops since the last fix

I haven't tested Commander Blade, but I've added it to TODO.md. Overall, I think newserv BB support is stable enough for normal play now. I'll continue to respond to specific issues here, of course - feel free to submit any bugs or feature requests that come up.
