### ISSUE TITLE
Can't log in to my own server. Keep getting error 916.

### ISSUE THREAD

**Issue by AlmaElma123** [fuzziqersoftware/newserv#672]
Issue: When I go to start the game, after all my log in detail is in, and it finishes the patch step of logging in, it hangs for about 20 seconds then gives me an error saying "Error 916. Server is full. Try connecting later"

Game version: Blue Burst. Used the English Teth version of PSO BB linked in the guide.

PC OS: Windows 10

![Image](https://github.com/user-attachments/assets/23917cc1-6fd2-4aaa-b14d-01a8c17300e3)

**Comment by fuzziqersoftware** [comment]
You need to change LocalAddress and ExternalAddress in system/config.json; there are comments in config.json that say what to put there. I just noticed that the readme doesn't actually mention this; will update it soon.

**Comment by AlmaElma123** [comment]
> You need to change LocalAddress and ExternalAddress in system/config.json; there are comments in config.json that say what to put there. I just noticed that the readme doesn't actually mention this; will update it soon.

Thank you for the help. That helped but I am still having issues getting friends to join. I cant even join my server on a different computer in the same house. Is it possible to maybe expand that section of the read me or is that another issue that is easily solved?

**Comment by fuzziqersoftware** [comment]
I think this is described in the readme, but the readme is very long so it may be easy to miss. Your LocalAddress will likely be something like 192.168.x.x, 172.16.x.x, or 10.x.x.x, and your ExternalAddress should come from e.g. https://www.whatismyip.com/. You'll have to set up port forwarding on your router if you want players from outside your network to be able to connect.

Also, I assume you're using a release and not building from source; there is a bug in the now-previous release that causes the external address to be used sometimes when it should use the local address instead. This has been fixed on master, and I've just built a new release, so you could try using that.

**Comment by AlmaElma123** [comment]
I followed the steps and still have issues connecting. Local and external IP is set, I port forwarded the ports from PortConfiguration, Azure is pointing to the local address on the other computer and I am still not connecting to the server at all with an error 903. I got the patch_server and game_server sections all pointed to the local IP and everything on the other computer.

I can't seem to find the right log file on the other computer? What log file I did file under PSOBB/Log is just completely empty.

Also I am using the release yes and I just got the new version you put out and still nothing.
